### ISSUE TITLE
[HELP WANTED]: Answers provided are incorrect

### ISSUE THREAD

**Issue by susravya-d** [feder-cr/Jobs_Applier_AI_Agent#532]
### Issue description

I don't know how it is choosing the answers. 
I want to answer yes to this question but it is submitting no. 
Here is the debug logs. 

2024-10-14 00:46:24.786 | DEBUG    | src.aihawk_easy_applier:_fill_additional_questions:605 - Filling additional questions
2024-10-14 00:46:24.790 | DEBUG    | src.aihawk_easy_applier:_process_form_section:611 - Processing form section
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_sanitize_text:849 - Sanitized text: are you legally authorized to work in the united states?are you legally authorized to work in the united states?requiredyesno
2024-10-14 00:46:24.825 | DEBUG    | src.aihawk_easy_applier:_select_radio:808 - Selecting radio option: no
2024-10-14 00:46:24.914 | DEBUG    | src.aihawk_easy_applier:_find_and_handle_radio_question:653 - Selected existing radio answer
2024-10-14 00:46:24.925 | DEBUG    | src.aihawk_easy_applier:_process_form_section:616 - Handled radio question
2024-10-14 00:46:24.925 | DEBUG    | src.aihawk_easy_applier:_process_form_section:611 - Processing form section

How to fix this?

**Comment by mdgjohnny** [comment]
It looks like the issue might be related to your `plain_text_resume.yaml ` configuration.  Please check the `legal_authorization` section in your yaml file and make sure it's set correctly.

**Comment by susravya-d** [comment]
```
legal_authorization:
  eu_work_authorization: "No"
  us_work_authorization: "Yes"
  requires_us_visa: "No"
  requires_us_sponsorship: "No"
  requires_eu_visa: "Yes"
  legally_allowed_to_work_in_eu: "No"
  legally_allowed_to_work_in_us: "Yes"
  requires_eu_sponsorship: "Yes"
  canada_work_authorization: "No"
  requires_canada_visa: "Yes"
  legally_allowed_to_work_in_canada: "No"
  requires_canada_sponsorship: "Yes"
  uk_work_authorization: "No"
  requires_uk_visa: "Yes"
  legally_allowed_to_work_in_uk: "No"
  requires_uk_sponsorship: "Yes"
```

This is my config file.
