### ISSUE TITLE
[FEATURE]: Labeling PR's when merge conflicts exist on PR

### ISSUE THREAD

**Issue by surapuramakhil** [feder-cr/Jobs_Applier_AI_Agent#809]
### Feature summary

Auto label PR when merge confits exist in PR - helps reviewers which PR needs to review first

### Feature description

there is one GitHub actions plugin which can do this task

https://github.com/eps1lon/actions-label-merge-conflict

```yml
name: "Maintenance"
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "PR: ready to ship"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
```
