### ISSUE TITLE
[DOCS]: Unclear what to do with unneeded options in YAML files

### ISSUE THREAD

**Issue by kttn** [feder-cr/Jobs_Applier_AI_Agent#899]
### Affected documentation section

2. work_preferences.yaml;   3. plain_text_resume.yaml 

### Documentation improvement description

I am unclear as to what I should be doing with unneeded options in the two YAML Files:   _"work_preferences.yaml"_   and    _"plain_text_resume.yaml"._

For example,   `plain_text_resume.yaml`,   in the   `personal_information`   section  :

```
personal_information:
  name: "[Your Name]"
  surname: "[Your Surname]"
  date_of_birth: "[Your Date of Birth]"
  country: "[Your Country]"
  city: "[Your City]"
  address: "[Your Address]"
  zip_code: "[Your zip code]"
  phone_prefix: "[Your Phone Prefix]"
  phone: "[Your Phone Number]"
  email: "[Your Email Address]"
  github: "[Your GitHub Profile URL]"               # Un-needed (Github profile, in my case, is not required, and would be odd to include)
  linkedin: "[Your LinkedIn Profile URL]"

```

What do I do to omit the inclusion of the GitHub Profile URL field/option?

Can I just comment out the ones I don't need?

Can they just be removed, without affecting the main program logic?

Can I mark them with something like n/a, and they AI will figure out what to do?

I may have missed something,   but this is unclear to me!

 

### Why is this change necessary?

If not included, and I haven't missed it, including this information will make the project more accessible to a larger audience
